version: '3.9'

services:
mongodb:
    image: mongodb:5.0.8
    container_name: mongodb
    environment:
    MONGO_INITBD_ROOT_USERNAME: admin
    MONGO_INITBD_ROOT_PASSAWORD: admin
    restart: always

    api:
      build:

      ports:
        - 5000:5000
      restart: always
